### ISSUE TITLE
Not able to install pdf-bot

### ISSUE THREAD

**Issue by maddy1512** [esbenp/pdf-bot#1]
I installed pdf-bot using npm but after installing whenever I run command 
`pdf-bot install` I get following error:

```
/usr/lib/node_modules/pdf-bot/bin/pdf-bot.js:328
function openConfig(delayQueueCreation = false) {
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```
I don't know why it is throwing this error. Is it because of the node version?

**Comment by esbenp** [comment]
I think you need to have Node V6+ to support default parameters. What version do you have?

**Comment by maddy1512** [comment]
Oh! I have v4.4.4

**Comment by esbenp** [comment]
Yeah apologies. I might refactor those parts to support below versions below 6. Lets leave the issue open for now for visibility's sake

**Comment by maddy1512** [comment]
Ok and if possible you can also update README. Cheers!!

**Comment by westy92** [comment]
@esbenp https://github.com/westy92/html-pdf-chrome requires Node.js V6+ as well.  I'd like to note that Node.js V4 is out of active LTS support and only has maintenance updates until April 2018.  Support for Node.js v5 has already been dropped.
https://github.com/nodejs/LTS#lts-schedule1

**Comment by esbenp** [comment]
Yeah I actually tried to remove the defaults today but saw the test failed from something in `html-pdf-chrome`. I guess I will just require Node v6+ :-)

Added d1542579c310e402cffa86d9849b226ad1764f39 and 6100fc06dc920ee177217e43026af6db5189b8c6
